name: Sync Parquet Files to Kaggle

on:

  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "Power Supply Statewise/**/*.parquet"

jobs:

  upload-to-kaggle:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Kaggle CLI
        run: |
          pip install kaggle

      - name: Configure Kaggle
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |

          mkdir -p ~/.config/kaggle

          cat > ~/.config/kaggle/kaggle.json <<EOF
          {
            "username": "$KAGGLE_USERNAME",
            "key": "$KAGGLE_KEY"
          }
          EOF

          chmod 600 ~/.config/kaggle/kaggle.json

      - name: Show Parquet files
        run: |
          echo "Parquet files:"
          find "Power Supply Statewise" -type f -name "*.parquet"

      - name: Upload to Kaggle
        run: |
          kaggle datasets version \
            -p "Power Supply Statewise" \
            -m "Updated Parquet files"
